name: CI

on: push

env:
  CI: true

jobs:
  build:
    name: Lint, test, build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10', '12', '14']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint:formatting
      - run: npm run type-check
      - run: npm run test
      - run: npm run build
      - run: ./bin/loose-ts-check --help
