name: CI

on: push

env:
  CI: true

jobs:
  build:
    name: Lint, test, build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16, 18, latest]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint:formatting
      - run: npm run type-check
      - run: npm run build
      - run: npm run test:unit
      - run: ./bin/loose-ts-check --help

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, latest]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - run: npm run test:integration
